/* Traductions francais -> anglais du site Phe-Nix (genere automatiquement) */
var DICO = {
 "Chaque sortie est annoncée et racontée sur notre groupe Facebook. C'est là que nous partageons les photos, les besoins du moment et les prochaines distributions.": "Every outing is announced and shared on our Facebook group. That's where we post the photos, the current needs and the upcoming distributions.",
 "semaine après semaine.": "week after week.",
 "Nos actions,": "Our work,",
 "L'équipe bénévole de Phé-Nix devant le pick-up, avant une distribution": "The Phé-Nix volunteer team in front of the pickup truck, before a distribution",
 "sans arrêt": "without a break",
 "Sur le terrain,": "In the field,",
 "Régions": "Regions",
 "Notre impact": "Our impact",
 "Un bénévole de Phé-Nix tend la main à une personne allongée sur un banc, dans la neige": "A Phé-Nix volunteer reaches out to a person lying on a bench, in the snow",
 "Tout est trié puis entreposé : les repas sont congelés à l'avance, les vêtements et le matériel sont classés, prêts pour la prochaine sortie.": "Everything is sorted then stored: meals are frozen ahead of time, clothing and supplies are organized, ready for the next outing.",
 "Nous entreposons": "We store",
 "Navigation": "Navigation",
 "Nous écrire →": "Write to us →",
 "Des repas chauds à manger sur place et des repas congelés à emporter, une fois par semaine, directement dans la rue.": "Hot meals to eat on the spot and frozen meals to take away, once a week, right on the street.",
 "Lire moins": "Read less",
 "Lire plus": "Read more",
 "Il n'a jamais arrêté depuis. Chaque semaine : nourriture, vêtements adaptés à la saison, couvertures, écoute et un accompagnement vers la thérapie pour ceux qui veulent s'en sortir.": "He has never stopped since. Every week: food, season-appropriate clothing, blankets, a listening ear, and support toward treatment for those who want a way out.",
 "Ce jour-là, Mike est frappé par la réalité : il y a là un vrai problème, que beaucoup préfèrent ignorer. Lui décide d'arrêter de l'ignorer.": "That day, Mike is struck by the reality of it: there is a real problem here, one many would rather ignore. He decides to stop ignoring it.",
 "Un an plus tard, à sa mémoire, Mike réunit neuf proches. Vingt dollars chacun. Ensemble, ils préparent des repas et vont les distribuer.": "A year later, in his memory, Mike gathers nine people close to him. Twenty dollars each. Together they prepare meals and go out to hand them out.",
 "Phé-Nix est né d'un sentiment d'impuissance. En 2021, un ami de Mike décède dans la rue, et il reste cette impression de n'avoir rien pu faire.": "Phé-Nix was born out of a feeling of helplessness. In 2021, a friend of Mike's passes away on the street, and what remains is the sense of having been able to do nothing.",
 "La première distribution, en sa mémoire.": "The first distribution, in his memory.",
 "En mémoire d'un ami.": "In memory of a friend.",
 "Téléphone": "Phone",
 "Courriel": "Email",
 "À une équipe et à une ville, selon les besoins du moment. Les distributions ont lieu dans certaines villes seulement.": "To a team and a city, based on current needs. Distributions take place in certain cities only.",
 "Nous vous assignons": "You're assigned",
 "Pour vous expliquer les étapes à franchir avant de venir sur le terrain.": "To explain the steps to complete before joining us in the field.",
 "Nous vous rappelons": "We call you back",
 "Écrivez-nous votre région et vos disponibilités. Nous vous recontactons pour vous expliquer les étapes, puis vous êtes assigné à une équipe de distribution selon les besoins du moment. L'équipe vous accueille et vous guide sur le terrain.": "Write to us with your region and availability. We'll get back to you to explain the steps, then you're assigned to a distribution team based on current needs. The team welcomes you and guides you in the field.",
 "16 décembre 2022": "December 16, 2022",
 "Pas de salaires. Pas de loyer. Pas de frais cachés.": "No salaries. No rent. No hidden fees.",
 "Des repas chauds remis en mains propres, une fois par semaine, peu importe la température, à Montréal, en Montérégie, à Gatineau et à Trois-Rivières.": "Hot meals handed over in person, once a week, whatever the weather, in Montreal, the Montérégie, Gatineau and Trois-Rivières.",
 "Vous pouvez aussi donner directement des vêtements adaptés à la saison, de la nourriture ou des articles d'hygiène.": "You can also give season-appropriate clothing, food or hygiene products directly.",
 "Du matériel": "In-kind goods",
 "Une distribution complète, de la préparation jusqu'à la rue.": "A full distribution, from preparation to the street.",
 "À peu près, voici ce que votre don permet :": "Roughly, here's what your gift makes possible:",
 "Ce que votre don permet": "What your gift makes possible",
 "qui amènent tout ça sur le terrain, cette semaine.": "that bring it all out into the field, this week.",
 "logistique": "logistics",
 "achats": "purchases",
 ". Votre argent finance ce qui manque : les": ". Your money funds what's missing: the",
 "donnés": "donated to us",
 "La nourriture et les vêtements nous sont": "Food and clothing are",
 "Itinéraire": "Directions",
 "Trousses, articles de première nécessité, maquillage.": "Kits, basic necessities, makeup.",
 "Savon, brosses à dents, produits de soin, produits d'hygiène féminine.": "Soap, toothbrushes, care products, feminine hygiene products.",
 "Vêtements adaptés à la saison": "Season-appropriate clothing",
 "Oui, peu importe la température. C'est souvent quand les conditions sont les plus dures que le besoin est le plus grand.": "Yes, whatever the temperature. It's often when conditions are harshest that the need is greatest.",
 "Des repas chauds à consommer sur place, des repas congelés à emporter pour le lendemain, de l'eau embouteillée et du café. Les repas sont congelés à l'avance : cela préserve la fraîcheur et permet de conserver de la nourriture pour plus tard.": "Hot meals to eat right away, frozen meals to take away for the next day, bottled water and coffee. Meals are frozen ahead of time: it preserves freshness and makes it possible to keep food for later.",
 "Qu'est-ce que vous distribuez exactement ?": "What exactly do you hand out?",
 ": des aliments encore bons sont récupérés avant d'être jetés, puis préparés et redistribués.": ": food that is still good is recovered before being thrown out, then prepared and redistributed.",
 "programme anti-gaspillage alimentaire": "food waste reduction program",
 "Des dons de citoyens et de commerces partenaires, et d'un": "Donations from citizens and partner businesses, and from a",
 "D'où vient la nourriture ?": "Where does the food come from?",
 "À manger sur place, et à emporter pour le lendemain.": "To eat on the spot, and to take away for the next day.",
 "Chaud et congelé": "Hot and frozen",
 "Une fois par semaine, notre équipe de bénévoles va à la rencontre des personnes en situation d'itinérance, peu importe la température. Nous offrons un repas chaud à consommer sur place, ainsi que des repas congelés à emporter : congelés à l'avance, ils se conservent et permettent de manger encore le lendemain. Nous distribuons également de l'eau embouteillée et du café.": "Once a week, our volunteer team goes out to meet people experiencing homelessness, whatever the temperature. We offer a hot meal to eat right away, but also frozen meals to take away: frozen ahead of time, they keep and make it possible to eat again the next day. We also hand out bottled water and coffee.",
 "Des repas chauds à manger sur place et des repas congelés à emporter, distribués une fois par semaine, directement dans la rue.": "Hot meals to eat on the spot and frozen meals to take away, handed out once a week, right on the street.",
 "organisé au profit de Phé-Nix. Nous sommes ouverts à toutes les propositions. Ce qui compte, c'est l'impact.": "held for the benefit of Phé-Nix, we're open to any idea. What matters is the impact.",
 "tirage moitié-moitié (50/50)": "50/50 raffle",
 "Don de matériel, activité de team building sur le terrain, partenariat médias, collecte de dons auprès de vos employés, ou encore un": "In-kind giving, a team-building day in the field, a media partnership, a collection among your employees, or even a",
 "100 % de votre soutien part sur le terrain": "100% of your support goes to the field",
 "Visibilité de votre geste auprès de notre communauté": "Visibility for your contribution within our community",
 "Remerciement sur nos réseaux sociaux": "A thank-you on our social media",
 "Votre logo sur le pick-up de l'organisme": "Your logo on the organization's pickup truck",
 "Avec plaisir ! Déposez vêtements, nourriture non périssable et articles d'hygiène, dont des produits d'hygiène féminine dans l'un de nos": "Gladly! Drop off clothing, non-perishable food and hygiene products, including feminine hygiene products at one of our",
 "Vêtements, nourriture, articles d'hygiène dont des produits féminins, à déposer dans un de nos 3 points de collecte.": "Clothing, food, hygiene products including feminine products, to drop off at one of our 3 collection points.",
 "Dons en argent, nourriture, vêtements et articles d'hygiène, dont des produits d'hygiène féminine, de citoyens et de plus de 100 commanditaires.": "Cash, food, clothing and hygiene products, including feminine hygiene products, from citizens and more than 100 sponsors.",
 "Un repas chaud remis en mains propres dans la rue": "A hot meal handed over in person on the street",
 "Un appel passé pour trouver la bonne ressource, et le nom noté dans un carnet": "A call made to find the right resource, and the name written down in a notebook",
 "Une boîte de denrées préparée pour un dépannage alimentaire": "A box of food prepared for an emergency food package",
 "\"Ce que nous partageons tous, c'est un": "\"What we all share is an",
 "& bien-être": "& wellness",
 "& institutions": "& institutions",
 "& restauration": "& restaurants",
 "& services": "& services",
 ", de l'": ", ",
 ", nous vous mettons en contact avec des services de thérapie adaptés à votre situation.": ", we put you in touch with treatment services suited to your situation.",
 ", nous conduisons la personne jusqu'à la région où se trouve la ressource qui l'accueille.": ", we drive the person to the area where the resource taking them in is located.",
 ", ou contactez-nous pour organiser un dépôt.": ", or contact us to arrange a drop-off.",
 ". Vous pouvez aussi nous écrire ou nous appeler.": ". You can also email or call us.",
 "0 % en administration. 0 % en salaires.": "0% on administration. 0% on salaries.",
 "1 à 2 boîtes": "1 to 2 boxes",
 "10 $ à 15 $ peuvent s'appliquer, seulement si une livraison est nécessaire.": "A $10 to $15 fee may apply, only if delivery is needed.",
 "100 % bénévole": "100% volunteer-run",
 "100 % bénévole, aucun salaire": "100% volunteer-run, no salaries",
 "100 % sur le terrain": "100% on the ground",
 "100 % sur le terrain.": "100% on the ground.",
 "2 à 3 dépannages par année": "2 to 3 food packages per year",
 "3 ans": "3 years",
 "3 façons d'aider Phé-Nix : faire un don par Interac, devenir bénévole, ou déposer vêtements et nourriture dans nos points de collecte.": "3 ways to help Phé-Nix: donate by Interac, volunteer, or drop off clothing and food at our collection points.",
 "3 façons de faire une différence": "3 ways to make a difference",
 "6 villes desservies": "6 cities served",
 "plus ou moins 72 heures": "roughly 72 hours",
 "Accueil": "Home",
 "Adapté à votre réalité": "Matched to your reality",
 "Aider": "Get involved",
 "Aider Phé-Nix | Don, bénévolat et contributions matérielles": "Help Phé-Nix | Donations, volunteering and in-kind giving",
 "Aider, c'est simple.": "Helping is simple.",
 "Aidé près de chez vous": "Help close to home",
 "Alimentation": "Food",
 "Articles d'hygiène": "Hygiene products",
 "Association de votre marque à notre mission": "Your brand associated with our mission",
 "Associez votre entreprise à Phé-Nix et soutenez concrètement les personnes en situation d'itinérance au Québec. Plus de 100 partenaires nous soutiennent.": "Partner your business with Phé-Nix and provide real support to people experiencing homelessness in Quebec. Over 100 partners stand with us.",
 "Aucun salaire : tout le travail est fait par des bénévoles.": "No salaries, all the work is done by volunteers.",
 "Aucune enquête de crédit n'est requise.": "No credit check required.",
 "Aucune expérience requise, aucun équipement à prévoir. Juste l'envie d'agir, un samedi à la fois.": "No experience needed, no equipment required, just the will to act, one Saturday at a time.",
 "Aucune expérience requise. Juste l'envie d'agir, un samedi à la fois, près de chez vous.": "No experience needed. Just the will to act, one Saturday at a time, close to home.",
 "Autre idée ?": "Another idea?",
 "Avant de donner, vous vous demandez peut-être…": "Before you give, you might be wondering…",
 "Avec plaisir. Aucune expérience n'est requise. Rendez-vous sur la page": "Gladly. No experience needed, head to the",
 "Bon à savoir": "Good to know",
 "Bénévole": "Volunteer",
 "Bénévole,": "Volunteer-run,",
 "C'est sa conviction qui a tout lancé en 2022 : l'itinérance n'est pas une fatalité. Il est sur le terrain chaque semaine, là où les besoins sont les plus criants.": "His conviction started it all in 2022: homelessness is not inevitable. He's out in the field every week, where the need is greatest.",
 "Caisses de légumes frais triés avant la distribution": "Crates of fresh vegetables sorted before distribution",
 "Ce qu'il faut savoir avant de nous contacter.": "What to know before you contact us.",
 "Ce qu'il faut savoir sur le transport vers la thérapie.": "What to know about rides to treatment.",
 "Ce qu'il faut savoir sur nos distributions dans la rue.": "What to know about our street distributions.",
 "Ce que nous acceptons": "What we accept",
 "Ce que nous faisons, concrètement.": "What we actually do.",
 "Ce que nous offrons": "What we offer",
 "Ce qui fait vraiment la différence.": "What really makes a difference.",
 "Chaque repas chaud, chaque manteau d'hiver, chaque personne accompagnée vers la thérapie existe grâce à la générosité de plus de 100 commerces, organismes et citoyens. Vous transformez des dons en gestes concrets, semaine après semaine. Du fond du cœur : merci.": "Every hot meal, every winter coat, every person guided toward treatment exists thanks to the generosity of more than 100 businesses, organizations and citizens. You turn donations into real action, week after week. From the bottom of our hearts: thank you.",
 "Chaque semaine": "Every week",
 "Chaque semaine, Phé-Nix distribue des repas chauds directement dans la rue aux personnes en situation d'itinérance, dans plusieurs villes du Québec.": "Every week, Phé-Nix hands out hot meals right on the street to people experiencing homelessness, in several Quebec cities.",
 "Chaque semaine, nous sommes là.": "Every week, we're there.",
 "Chaque service répond à un besoin précis. Cliquez pour en savoir plus et entrer en contact avec nous.": "Each service meets a specific need. Click to learn more and get in touch.",
 "Choisissez la vôtre.": "Choose yours.",
 "Combien de fois par année puis-je y avoir droit ?": "How many times a year can I receive it?",
 "Combien de temps avant d'avoir une réponse ?": "How long before I get an answer?",
 "Commanditaires": "Sponsors",
 "Commandite": "Sponsorship",
 "Deux bénévoles par transport, jamais un seul. Comme tout ce que nous faisons : 100 % bénévole, sans salaire.": "Two volunteers per ride, never just one. Like everything we do: 100% volunteer-run, no salaries.",
 "Comment aider": "How to help",
 "Comment choisissez-vous la ressource ?": "How do you choose the resource?",
 "Comment faire la demande ?": "How do I make a request?",
 "Comment faire une demande ?": "How do I make a request?",
 "Notre façon d'agir": "How we act",
 "Comment nous pouvons vous aider.": "How we can help you.",
 "Comment organiser un transport ?": "How do I arrange a ride?",
 "Comment s'impliquer": "How to get involved",
 "Comment savoir quand vous passez près de chez moi ?": "How do I know when you're near me?",
 "Comment cela fonctionne": "How it works",
 "Le déroulement": "How it works",
 "Commerce": "Retail",
 "Conserves et denrées non périssables.": "Canned goods and non-perishable food.",
 "Contactez-nous directement pour faire une demande de dépannage alimentaire.": "Contact us directly to request emergency food assistance.",
 "Contactez-nous directement pour organiser un transport vers une thérapie.": "Contact us directly to arrange a ride to treatment.",
 "Contactez-nous directement pour être mis en contact avec une ressource adaptée.": "Contact us directly to be connected with the right resource.",
 "Contactez-nous par courriel, par téléphone ou par Facebook. Les coordonnées sont juste en dessous. Nous évaluons ensemble ce qui est possible selon la ressource qui vous accueille et la distance à parcourir.": "Reach us by email, phone or Facebook. The details are just below. We look together at what is possible based on the resource taking you in and the distance to cover.",
 "Contenu photo et vidéo pour vos réseaux": "Photo and video content for your social media",
 "Contributions matérielles": "In-kind donations",
 "Contributions matérielles | Phé-Nix, points de collecte": "In-kind donations | Phé-Nix, collection points",
 "Copier l'adresse Interac →": "Copy the Interac address →",
 "Courriel": "Email",
 "Dans la note du virement, écrivez": "In the transfer note, write",
 "Dans quels secteurs le service est-il offert ?": "Which areas is the service offered in?",
 "De 1 à 2 boîtes de denrées selon les besoins, remises directement à la personne ou à la famille.": "One to two boxes of food depending on need, handed directly to the person or family.",
 "De 2 à 3 dépannages par année, par personne ou par famille. Dans des situations exceptionnelles, il est possible d'en recevoir davantage. Parlez-nous de votre situation.": "Two to three packages per year, per person or family. In exceptional situations more may be possible, tell us about your circumstances.",
 "Des bénévoles de l'équipe Phé-Nix, comme pour tout ce que nous faisons. Ils sont toujours deux : un transport n'est jamais assuré par un bénévole seul.": "Volunteers from the Phé-Nix team, like everything we do. There are always two of them: a ride is never handled by a single volunteer.",
 "Des chiffres qui parlent.": "Numbers that speak.",
 "Des distributions régulières, semaine après semaine, depuis 2022.": "Regular distributions, week after week, since 2022.",
 "Devenez bénévole chez Phé-Nix. Aucune expérience requise, juste l'envie d'agir. Écrivez-nous votre région et vos disponibilités.": "Volunteer with Phé-Nix. No experience needed, just the will to act. Send us your area and your availability.",
 "Devenir bénévole": "Become a volunteer",
 "Devenir bénévole | Phé-Nix, aucune expérience requise": "Become a volunteer | Phé-Nix, no experience needed",
 "Devenir bénévole →": "Become a volunteer →",
 "Distribution alimentaire": "Food distribution",
 "Distribution alimentaire dans les rues": "Street food distribution",
 "Distribution alimentaire dans les rues | Phé-Nix": "Street food distribution | Phé-Nix",
 "Distribution alimentaire dans les rues.": "Street food distribution.",
 "Distribution alimentaire, dépannage alimentaire, référencement et transport vers la thérapie. Découvrez les services de Phé-Nix.": "Food distribution, emergency food assistance, referrals and rides to treatment, discover Phé-Nix's services.",
 "Distributions": "Distributions",
 "Dois-je déjà avoir trouvé une thérapie ?": "Do I need to have found treatment already?",
 "Don": "Donate",
 "Du don à la rue, en 3 étapes.": "From donation to street, in 3 steps.",
 "Défilez": "Scroll",
 "Dépannage alimentaire": "Emergency food assistance",
 "Dépannage alimentaire | Phé-Nix": "Emergency food assistance | Phé-Nix",
 "Dépannage alimentaire.": "Emergency food assistance.",
 "Déposez vos dons directement dans l'un de ces commerces partenaires.": "Drop your donations directly at one of these partner businesses.",
 "Déposez vêtements,": "Drop off clothing,",
 "Déposez vêtements, nourriture non périssable et articles d'hygiène dans l'un des 3 points de collecte de Phé-Nix en Montérégie.": "Drop off clothing, non-perishable food and hygiene products at one of Phé-Nix's 3 collection points in the Montérégie.",
 "Une thérapie se trouve rarement au coin de la rue. En complément du": "A treatment centre is rarely around the corner. Alongside our",
 "En savoir plus →": "Learn more →",
 "Encadrement complet par notre équipe": "Full guidance from our team",
 "Entrevue avec Michel Couture": "Interview with Michel Couture",
 "Est-ce que vous sortez même par mauvais temps ?": "Do you go out even in bad weather?",
 "Le service est-il payant ?": "Does it cost anything?",
 "Et une fois que la ressource est trouvée ?": "And once the resource is found?",
 "Exclusivement à Montréal Sud-Ouest, à Saint-Jean-sur-Richelieu et à Longueuil pour le moment.": "Currently in Montreal's South-West, Saint-Jean-sur-Richelieu and Longueuil only.",
 "Expérience terrain inoubliable": "An unforgettable day in the field",
 "Faire partie du mouvement": "Join the movement",
 "Faire un don": "Donate",
 "Faire un don | Phé-Nix, par Interac, 100 % sur le terrain": "Donate | Phé-Nix, by Interac, 100% on the ground",
 "Faire un don →": "Donate →",
 "Faire une demande": "Make a request",
 "Fait avec soin pour ceux qui en ont le plus besoin.": "Made with care for those who need it most.",
 "Faites un don à Phé-Nix par virement Interac. Pas de frais, pas de salaires : chaque dollar achète nourriture, eau et vêtements, et va directement sur le terrain.": "Donate to Phé-Nix by Interac transfer. No fees, no salaries: every dollar buys food, water and clothing, and goes straight to the field.",
 "Faut-il s'inscrire ou prendre rendez-vous ?": "Do I need to register or book an appointment?",
 "Frais de déplacement": "Delivery fee",
 "Grâce au soutien de plus de 100 partenaires, Phé-Nix peut agir semaine après semaine.": "Thanks to more than 100 partners, Phé-Nix can act week after week.",
 "Guy Couture": "Guy Couture",
 "Guy Couture, vice-président-fondateur de Phé-Nix": "Guy Couture, co-founder and vice-president of Phé-Nix",
 "Plus ou moins 72 heures. Nous disposons d'une solide banque de ressources, ce qui nous laisse le temps de chercher celle qui vous convient réellement plutôt que de vous référer au premier endroit disponible.": "Roughly 72 hours. We have a solid bank of resources, which gives us time to look for the one that actually suits you instead of referring you to the first place available.",
 "En": "In",
 "Plus ou moins 72 h": "Roughly 72 hours",
 "Ils nous font confiance.": "They trust us.",
 "Impact direct et immédiat sur le terrain": "Direct, immediate impact in the field",
 "Je préfère donner du matériel plutôt que de l'argent.": "I'd rather give goods than money.",
 "Je voudrais aider lors d'une distribution.": "I'd like to help at a distribution.",
 "L'entrevue": "The interview",
 "Nous vous conduisons jusqu'à la région où se trouve votre thérapie.": "We drive you to the area where your treatment centre is.",
 "La bonne ressource, rapidement.": "The right resource, fast.",
 "La demande peut être faite pour soi-même ou pour quelqu'un d'autre.": "A request can be made for yourself or for someone else.",
 "La fondation": "The founding",
 "La route vers un nouveau départ": "The road to a fresh start",
 "La suite du référencement": "What follows the referral",
 "Le bouton ouvre votre courriel avec un message déjà préparé. Vous n'avez qu'à compléter et envoyer.": "The button opens your email with a message already written, just fill it in and send.",
 "Le camion Phé-Nix Action Communautaire Citoyenne": "The Phé-Nix Action Communautaire Citoyenne truck",
 "Le délai courant pour vous mettre en contact avec une ressource.": "The usual time to connect you with a resource.",
 "Le dépannage alimentaire comprend 1 à 2 boîtes de denrées, offertes en don aux personnes qui ont besoin de soutien alimentaire.": "Emergency food assistance means 1 to 2 boxes of food, given freely to people who need food support.",
 "Pas une navette quotidienne, pas un transport vers des rendez-vous.": "Not a daily shuttle, and not a ride to appointments.",
 "Le père de Mike, à ses côtés depuis le tout premier jour. La preuve vivante que l'entraide se transmet d'une génération à l'autre.": "Mike's father, at his side since day one. Living proof that helping others passes from one generation to the next.",
 "Le service est offert exclusivement dans les secteurs de": "The service is offered only in",
 "Le transport d'une personne vers sa thérapie.": "One person's ride to treatment.",
 "Le transport suit": "The ride follows",
 "Les denrées sont un don, elles ne se paient pas. Des frais de 10 $ à 15 $ peuvent s'appliquer uniquement si une livraison est nécessaire pour vous les apporter.": "The food is a gift, you never pay for it. A $10 to $15 fee may apply only if delivery is needed to bring it to you.",
 "Les distributions ont lieu à Montréal, en Montérégie, à Gatineau et à Trois-Rivières. Le tout est réalisé 100 % par des bénévoles.": "Distributions take place in Montreal, the Montérégie, Gatineau and Trois-Rivières. Everything is run 100% by volunteers.",
 "Les personnes qu'on accompagne vers une thérapie. Le transport vient en complément de notre service de": "People we're guiding toward treatment. Rides come alongside our",
 "Les prochaines distributions sont annoncées sur notre": "Upcoming distributions are announced on our",
 "Lire l'entrevue de Michel Couture": "Watch the interview with Michel Couture",
 "MERCI": "THANK YOU",
 "Manteaux, tuques, gants, bottes, couvertures.": "Coats, hats, gloves, boots, blankets.",
 "Matériel & logistique": "Equipment & logistics",
 "Maximum par personne ou par famille, sauf cas exceptionnel.": "Maximum per person or family, except in exceptional cases.",
 "Merci": "Thank you",
 "Merci à nos commanditaires": "Thank you to our sponsors",
 "Merci à nos commanditaires | Phé-Nix, devenez partenaire": "Thank you to our sponsors | Phé-Nix. Become a partner",
 "Merci.": "Thank you.",
 "Michel Couture « Mike »": "Michel Couture “Mike”",
 "Michel Couture « Mike » · Président-fondateur": "Michel Couture “Mike” · Founder and president",
 "Michel Couture, président-fondateur de Phé-Nix": "Michel Couture, founder and president of Phé-Nix",
 "Mobilisation": "Team mobilization",
 "Mon don par Interac est-il sécurisé ?": "Is my Interac donation secure?",
 "Montréal Sud-Ouest": "Montreal South-West",
 "Montréal Sud-Ouest, Saint-Jean-sur-Richelieu et Longueuil.": "Montreal South-West, Saint-Jean-sur-Richelieu and Longueuil.",
 "Montréal · Rive-Sud": "Montreal · South Shore",
 "Montréal, Montérégie, Gatineau et Trois-Rivières.": "Montreal, Montérégie, Gatineau and Trois-Rivières.",
 "Navigation principale": "Main navigation",
 "Non. Nos bénévoles vont directement à la rencontre des personnes sur le terrain. Il n'y a aucun formulaire à remplir, aucune inscription, aucune condition d'admissibilité. Nous demandons seulement de prendre connaissance du code d'éthique et des règlements généraux, qui encadrent le déroulement de la distribution.": "No. Our volunteers go straight out to meet people where they are. There is no form to fill in, no registration and no eligibility conditions. We only ask that you read our code of ethics and general rules, which set the framework for how a distribution unfolds.",
 "Nos 3 points de collecte.": "Our 3 collection points.",
 "Nos actions, semaine après semaine.": "Our work, week after week.",
 "Nos commanditaires": "Our sponsors",
 "Nos services": "Our services",
 "Nos services | Phé-Nix": "Our services | Phé-Nix",
 "Nos services.": "Our services.",
 "Notre camion sillonne le Québec pour transporter repas, vêtements et espoir jusqu'à ceux qui en ont besoin.": "Our truck criss-crosses Quebec carrying meals, clothing and hope to those who need them.",
 "Notre impact depuis 2022": "Our impact since 2022",
 "Notre mission": "Our mission",
 "Notre équipe est disponible pour discuter d'un partenariat adapté à votre organisation.": "Our team is available to discuss a partnership suited to your organization.",
 "Nourrir, habiller et accompagner les personnes en situation d'itinérance au Québec. 100 % bénévole, sur le terrain depuis 2022.": "Feeding, clothing and supporting people experiencing homelessness in Quebec. 100% volunteer-run, in the field since 2022.",
 "Nourriture": "Food",
 "Nourriture & eau": "Food & water",
 "Nourriture, vêtements et fournitures": "Food, clothing and supplies",
 "Nous contacter →": "Contact us →",
 "OBNL enregistré au Québec": "Registered non-profit in Quebec",
  "Nous collectons": "We collect",
 "Nous avons une bonne banque de ressources, ce qui nous permet de prendre le temps de vous orienter vers celle qui correspond réellement à votre contexte et à votre réalité, plutôt que de vous référer au premier endroit venu.": "We have a solid bank of resources, which lets us take the time to point you to the one that truly fits your context and your reality, rather than referring you to the first place available.",
 "Nous connaissons les ressources du milieu et nous prenons le temps de comprendre votre contexte avant d'orienter. L'objectif n'est pas de vous transmettre un numéro au hasard, mais de trouver l'endroit qui correspond réellement à votre réalité.": "We know the resources in the field and we take the time to understand your situation before pointing you anywhere. The goal isn't to hand you a random phone number, but to find the place that genuinely fits your reality.",
 "Nous distribuons": "We hand out",
 "Nous sommes là pour vous répondre.": "We're here to answer you.",
 "Si la ressource est loin de chez vous, notre service de": "If the resource is far from where you live, our",
 "Nous orientons selon votre contexte, et non selon une liste générique.": "We guide based on your situation, not a generic list.",
 "Nous répondons à tous les messages, généralement sous 24 à 48 h.": "We answer every message, usually within 24 to 48 hours.",
 "Nous nous occupons de tout le reste.": "We take care of everything else.",
 "Nous trouvons d'abord la bonne ressource, puis nous vous y conduisons.": "First we find the right resource, then we take you there.",
 "Sur une longue distance": "Over a long distance",
 "Nous vous mettons en contact avec les ressources appropriées, adaptées à votre réalité.": "We connect you with the right resources, matched to your reality.",
 "Nous vous mettons en contact, en plus ou moins 72 h, avec les ressources adaptées à votre réalité.": "We put you in touch, in roughly 72 hours, with resources suited to your reality.",
 "Nous vous répondons": "We'll get back to you",
 "Organisme à but non lucratif qui nourrit, habille et soutient les personnes en situation d'itinérance au Québec depuis 2022.": "A non-profit that has fed, clothed and supported people experiencing homelessness in Quebec since 2022.",
 "Organismes": "Organizations",
 "Oui. Beaucoup de demandes viennent d'un proche, d'un membre de la famille ou d'un ami. Contactez-nous et parlez-nous de la situation.": "Yes. Many requests come from a loved one, a family member or a friend. Contact us and tell us about the situation.",
 "Oui. La plupart des applications bancaires permettent de programmer un virement Interac récurrent vers notre courriel. Écrivez-nous si vous avez besoin d'aide.": "Yes. Most banking apps let you schedule a recurring Interac transfer to our email. Write to us if you need a hand.",
 "Ouvrez votre application bancaire → « Virement Interac » → collez l'adresse, et le tour est joué.": "Open your banking app → “Interac e-Transfer” → paste the address, and you're done.",
 "Où déposer": "Where to drop off",
 "Où ont lieu les distributions ?": "Where do the distributions take place?",
 "Où va chaque dollar": "Where every dollar goes",
 "Par Interac, en 30 secondes. Chaque dollar achète nourriture et vêtements, sans aucun frais.": "By Interac, in 30 seconds. Every dollar buys food and clothing, with no fees.",
 "Par courriel, par téléphone ou par Facebook. Les coordonnées se trouvent juste en dessous. Écrivez-nous ou appelez-nous, et on prend le relais.": "By email, phone or Facebook, our details are just below. Write or call us, and we'll take it from there.",
 "Par courriel, par téléphone ou par Facebook. Les coordonnées sont juste en dessous. Écrivez-nous et nous prenons le relais.": "By email, phone or Facebook, our details are just below. Write to us and we'll take it from there.",
 "Toujours à deux": "Always in pairs",
 "Parlons-nous": "Let's talk",
 "Parlons-nous directement →": "Let's talk directly →",
 "Parlons-nous.": "Let's talk.",
 "Pas d'argent à donner ? Vos dons matériels font une différence tout aussi concrète sur le terrain.": "No money to give? Your donated goods make just as real a difference in the field.",
 "Pas de carte, pas de frais, pas d'intermédiaire. Un simple virement Interac, et votre geste est sur le terrain dès la prochaine distribution.": "No card, no fees, no middleman. A simple Interac transfer, and your gesture is in the field at the very next distribution.",
 "Pas encore. Phé-Nix n'est pas encore enregistré au fédéral, donc les reçus fiscaux ne sont pas disponibles pour le moment. Cette option sera offerte dès que l'enregistrement sera complété. Merci de votre compréhension.": "Not yet. Phé-Nix is not yet federally registered, so tax receipts aren't available at the moment. This will be offered as soon as registration is complete, thank you for understanding.",
 "Pas nécessairement. Si ce n'est pas encore fait, nous commençons par vous mettre en contact avec la bonne ressource, en plus ou moins 72 heures, puis nous nous occupons du déplacement.": "Not necessarily. If it is not done yet, we start by putting you in touch with the right resource, in roughly 72 hours, then we handle the ride.",
 "Personnes aidées": "People helped",
 "Phé-Nix est un OBNL québécois qui nourrit, habille et soutient les personnes en situation d'itinérance. 100% bénévole, sur le terrain depuis 2022.": "Phé-Nix is a Quebec non-profit that feeds, clothes and supports people experiencing homelessness. 100% volunteer-run, in the field since 2022.",
 "Phé-Nix vous met en contact, en plus ou moins 72 h, avec des ressources de thérapie adaptées à votre réalité.": "Phé-Nix puts you in touch, in roughly 72 hours, with treatment resources suited to your reality.",
 "Phé-Nix | Aide aux personnes en situation d'itinérance au Québec": "Phé-Nix | Help for people experiencing homelessness in Quebec",
 "Phé-Nix, action communautaire citoyenne": "Phé-Nix, citizen community action",
 "Phé-Nix, c'est d'abord l'histoire d'un fils et de son père qui ont décidé de ne plus détourner le regard.": "Phé-Nix is first and foremost the story of a son and his father who decided to stop looking away.",
 "Pick-up rempli de boîtes de légumes frais pour la distribution": "Pickup truck filled with boxes of fresh vegetables for distribution",
 "Un déplacement ponctuel": "A one-off trip",
 "Plusieurs façons": "Several ways",
 "Point 01": "Point 01",
 "Point 02": "Point 02",
 "Point 03": "Point 03",
 "Pour chaque dollar reçu, voici exactement où il va.": "For every dollar received, here's exactly where it goes.",
 "Pour organiser un dépôt, une collecte en entreprise, ou poser une question.": "To arrange a drop-off, a workplace drive, or to ask a question.",
 "Pour un dépôt spécial ou une collecte,": "For a special drop-off or a drive,",
 "Pour vous ou un proche": "For you or someone close",
 "Prochaines distributions sur Facebook →": "Upcoming distributions on Facebook →",
 "Présents à": "Present in",
 "Président-fondateur": "Founder and president",
 "Prêt à faire la différence ?": "Ready to make a difference?",
 "Puis-je faire un don mensuel ?": "Can I give monthly?",
 "Puis-je faire une demande pour quelqu'un d'autre ?": "Can I make a request for someone else?",
 "Puis-je obtenir un reçu fiscal ?": "Can I get a tax receipt?",
 "Qu'est-ce que je reçois exactement ?": "What exactly do I receive?",
 "Quatre façons concrètes d'intervenir : sur le terrain, dans l'urgence, ou vers un nouveau départ.": "Four concrete ways we step in, in the field, in an emergency, or toward a fresh start.",
 "Quatre services, chaque semaine, auprès des plus démunis.": "Four services, every week, for those most in need.",
 "Quatre étapes, c'est tout.": "Four steps, that's all.",
 "Questions fréquentes": "Frequently asked questions",
 "Qui conduit ?": "Who drives?",
 "Qui peut en bénéficier ?": "Who can use it?",
 "Qui peut faire une demande ?": "Who can make a request?",
 "Reconnaissable entre tous.": "Impossible to miss.",
 "Reconnaissance sur nos réseaux sociaux": "Recognition on our social media",
 "Rejoignez l'équipe": "Join the team",
 "Repas distribués": "Meals handed out",
 "Retour en haut": "Back to top",
 "Reçu fiscal : à venir, dès l'obtention du numéro de charité": "Tax receipt: coming once our charity number is issued",
 "Reçu fiscal : à venir, dès l'obtention du numéro de charité.": "Tax receipt: coming once our charity number is issued.",
 "Rien ne doit vous arrêter.": "Nothing should stop you.",
 "Rien ne se perd en chemin.": "Nothing gets lost along the way.",
 "Référencement pour thérapie": "Referrals to treatment",
 "Référencement pour thérapie | Phé-Nix": "Referrals to treatment | Phé-Nix",
 "Référencement pour thérapie.": "Referrals to treatment.",
 "Sans vous, rien de tout cela": "Without you, none of this",
 "Secteurs desservis": "Areas served",
 "Selon les besoins, remises directement à la personne ou à la famille.": "Depending on need, handed directly to the person or family.",
 "Service 01": "Service 01",
 "Service 02": "Service 02",
 "Service 03": "Service 03",
 "Service 04": "Service 04",
 "Soins personnels": "Personal care",
 "Soutien financier à notre mission": "Financial support for our mission",
 "Sports": "Sports",
 "Suivez la mission": "Follow the mission",
 "Sur la route, chaque semaine": "On the road, every week",
 "Sur le terrain": "In the field",
 "Sur le terrain depuis 2022": "In the field since 2022",
 "Sur le terrain, chaque semaine.": "In the field, every week.",
 "Sur le terrain, nous remettons tout en mains propres, nous écoutons, et nous accompagnons vers la thérapie ceux qui le souhaitent.": "In the field, we hand everything over in person, we listen, and we guide toward treatment those who want it.",
 "Sur le terrain. Aucun équipement requis, l'équipe prend soin de tout.": "In the field. No equipment needed, the team takes care of everything.",
 "Tout ce qu'il faut savoir avant de faire une demande.": "Everything to know before making a request.",
 "Tout à fait. Le virement Interac passe directement par votre institution bancaire, chiffré de bout en bout. Phé-Nix ne voit jamais vos informations bancaires.": "Absolutely. The Interac transfer goes straight through your bank, encrypted end to end. Phé-Nix never sees your banking information.",
 "Toute personne ou famille qui a besoin de soutien pour se nourrir. Aucune enquête de crédit n'est requise. Nous ne vous demanderons pas de prouver vos revenus.": "Anyone or any family who needs a hand putting food on the table. No credit check required, we won't ask you to prove your income.",
 "Transport vers la thérapie": "Rides to treatment",
 "Transport vers la thérapie | Phé-Nix": "Rides to treatment | Phé-Nix",
 "Transport vers la thérapie.": "Rides to treatment.",
 "Téléphone": "Phone",
 "Un courriel avec votre région et vos disponibilités. Deux minutes suffisent.": "An email with your area and your availability. It takes two minutes.",
 "Un don qui a vraiment du sens": "A gift that truly matters",
 "Un don, sans complications.": "A gift, no complications.",
 "Un don, une heure de bénévolat, ou quelques vêtements à déposer. Chaque geste va directement sur le terrain, cette semaine, près de chez vous.": "A donation, an hour of volunteering, or a few clothes to drop off. Every gesture goes straight to the field, this week, close to home.",
 "Un don, une heure de votre temps, ou quelques vêtements à déposer. Tout va directement sur le terrain.": "A donation, an hour of your time, or a few clothes to drop off. It all goes straight to the field.",
 "Un geste suffit": "One gesture is enough",
 "Un immense merci": "An enormous thank you",
 "Un partenariat qui vous ressemble.": "A partnership that looks like you.",
 "Un soutien ponctuel en denrées pour les personnes ou familles dans le besoin. Aucune enquête de crédit. Service offert à Montréal Sud-Ouest, Saint-Jean-sur-Richelieu et Longueuil.": "One-time food support for people or families in need. No credit check. Offered in Montreal South-West, Saint-Jean-sur-Richelieu and Longueuil.",
 "Un soutien ponctuel en denrées pour les personnes ou familles qui en ont besoin, selon certaines conditions.": "One-time food support for people or families who need it, subject to certain conditions.",
 "Un soutien ponctuel en denrées pour les personnes ou les familles qui ont besoin d'aide pour se nourrir.": "One-time food support for people or families who need a hand putting food on the table.",
 "Une chaîne simple et directe, sans intermédiaire ni frais d'administration.": "A simple, direct chain, no middlemen, no administrative fees.",
 "Une fois la bonne ressource trouvée, Phé-Nix conduit la personne jusqu'à la région où se trouve sa thérapie, même à plusieurs heures de route.": "Once the right resource is found, Phé-Nix drives the person to the area where their treatment is, even several hours away.",
 "Une fois la bonne ressource trouvée, nous nous occupons de vous y conduire.": "Once the right resource is found, we take care of getting you there.",
 "Une fois la bonne ressource trouvée, nous conduisons la personne jusqu'à la région où se trouve sa thérapie, même à plusieurs heures de route.": "Once the right resource is found, we drive the person to the area where their treatment is, even several hours away.",
 "Une fois la ressource trouvée, nous nous occupons de vous y conduire.": "Once the resource is found, we take care of getting you there.",
 "Une histoire de famille.": "A family story.",
 "Une question ?": "Have a question?",
 "Une question ? Nous sommes là.": "Have a question? We're here.",
 "Une question sur la commandite ?": "A question about sponsorship?",
 "Une à deux boîtes de denrées pour les personnes et les familles qui en ont besoin. Aucune enquête de crédit. De 2 à 3 fois par année, dans le Sud-Ouest de Montréal, à Saint-Jean-sur-Richelieu et à Longueuil.": "One to two boxes of food for people and families who need it. No credit check. Two to three times a year, in Montreal's South-West, Saint-Jean-sur-Richelieu and Longueuil.",
 "Vice-président-fondateur": "Co-founder and vice-president",
 "Vies accompagnées": "Lives guided",
 "Virement Interac · 30 secondes": "Interac transfer · 30 seconds",
 "Voir directement sur YouTube →": "Watch it on YouTube →",
 "Voir les points de dépôt →": "See the drop-off points →",
 "Voir les événements sur Facebook": "See events on Facebook",
 "Voir plus sur Facebook →": "See more on Facebook →",
 "Vos employés participent à nos distributions : un team building authentique avec un impact humain réel dans votre communauté.": "Your staff take part in our distributions, genuine team building with real human impact in your community.",
 "Vos questions.": "Your questions.",
 "Votre argent ne paie pas": "Your money doesn't pay for",
 "Votre contribution finance nos achats et notre logistique. Votre marque, visible là où cela compte vraiment.": "Your contribution funds our purchases and our logistics. Your brand, visible where it truly counts.",
 "Votre don, c'est": "Your gift is",
 "Votre présence": "Your presence",
 "Votre équipe sur le terrain": "Your team in the field",
 "Vous nous fournissez directement ce dont nous avons besoin. Chaque article se retrouve entre les mains d'une personne dans le besoin.": "You supply us directly with what we need. Every item ends up in the hands of someone who needs it.",
 "Vous venez": "You come out",
 "Vous écrivez": "You write",
 "Vêtements & couvertures": "Clothing & blankets",
 "ans": "years",
 "aucun salaire": "no salaries",
 "change une vie.": "changes a life.",
 "chaque année": "each year",
 "chaque semaine": "each week",
 "couvertes": "covered",
 "de faire une différence.": "to make a difference.",
 "des bureaux. Il nourrit des personnes.": "offices. It feeds people.",
 "engagés": "committed",
 "envers les sans-abris et les plus démunis.\"": "toward the homeless and those most in need.\"",
 "et": "and",
 "et des": "and",
 "groupe Facebook": "Facebook group",
 "investissement absolu": "absolute commitment",
 "la Montérégie": "the Montérégie",
 "ne serait possible.": "would be possible.",
 "nourriture ou articles.": "food or supplies.",
 "ou écrivez-nous directement.": "or write to us directly.",
 "par année": "per year",
 "points de collecte": "collection points",
 "pour changer une vie.": "to change a life.",
 "peut prendre le relais et vous conduire jusqu'à la région où elle se trouve.": "service can take over and drive you to the area where it is located.",
 "référencement pour thérapie": "referrals to treatment",
 "transport vers la thérapie": "rides to treatment",
 "un repas chaud ce soir.": "a hot meal tonight.",
 "vers la thérapie": "toward treatment",
 "© 2026 Phé-Nix Action Communautaire Citoyenne · OBNL enregistré.": "© 2026 Phé-Nix Action Communautaire Citoyenne · Registered non-profit.",
 "« Don Phé-Nix »": "“Don Phé-Nix”",
 "À Montréal, en Montérégie, à Gatineau et à Trois-Rivières.": "In Montreal, the Montérégie, Gatineau and Trois-Rivières.",
 "À chacun d'entre vous. Par respect pour nos partenaires, nous ne publions pas leurs noms.": "To every one of you. Out of respect for our partners, we don't publish their names.",
 "Écrire pour devenir bénévole →": "Email us to volunteer →",
 "Étape 01": "Step 01",
 "Étape 02": "Step 02",
 "Étape 03": "Step 03",
 "Étape 04": "Step 04",
 "Être partenaire de Phé-Nix, c'est contribuer à votre façon. Nous nous adaptons à ce que vous pouvez offrir. Aucun montant minimum, aucune pression.": "Partnering with Phé-Nix means contributing your way, we adapt to what you can offer. No minimum amount, no pressure.",
 "écrivez-nous": "write to us",
 "Pas de carte, pas de frais, pas d'intermédiaire. Un virement Interac, et c'est sur le terrain.": "No card, no fees, no middleman. One Interac transfer, and it's on the ground.",
 "Votre argent paie l'": "Your money pays for ",
 "essence": "fuel",
 "et la": "and the ",
 "qui amènent tout cela dans la rue.": "that bring it all out into the street.",
 "Chaque samedi, dans la rue.": "Every Saturday, out in the street.",
 "Concrètement, voici ce que cela représente.": "Here is what that looks like.",
 "≈ 50 $": "≈ $50",
 "≈ 100 $": "≈ $100",
 "Une distribution complète, du chargement jusqu'à la rue.": "A full distribution, from loading up to the street.",
 "Vêtements, nourriture ou articles d'hygiène, déposés chez nous.": "Clothing, food or hygiene items, dropped off with us.",
 "Le camion, l'essence, les kilomètres.": "The truck, the fuel, the kilometres.",
 "Nous n'achetons rien : tout nous est donné. Votre argent sert uniquement à recueillir ces dons et à les amener jusqu'aux personnes. Voici l'ordre de grandeur.": "We buy nothing: everything is donated to us. Your money is used solely to collect those donations and bring them to people. Here is the rough order of magnitude.",
 "Essence & déplacements": "Fuel & travel",
 "La plus grosse part": "The largest share",
 "Logistique & entreposage": "Logistics & storage",
 "Une part importante": "A significant share",
 "Une part réelle": "A real share",
 "Une petite part": "A small share",
 "Ouvrez votre application bancaire → « Virement Interac » → collez l'adresse.": "Open your banking app → \"Interac e-Transfer\" → paste the address.",
 "Distribution de repas dans la rue par les bénévoles de Phé-Nix": "Phé-Nix volunteers handing out meals in the street",
 "Le camion de Phé-Nix chargé avant une distribution": "The Phé-Nix truck loaded up before a distribution",
 "Collectes et distributions": "Pickups and distributions",
 "Phé-Nix n'achète pas la nourriture. Les denrées, les vêtements et le matériel nous sont donnés par des commanditaires, des commerces et des organismes. Votre argent sert à aller les chercher et à les acheminer : l'essence, les kilomètres, l'entreposage et la logistique des distributions.": "Phé-Nix does not buy the food. The food, clothing and supplies are donated to us by sponsors, businesses and other organisations. Your money is used to go and collect them and to move them: fuel, kilometres, storage and distribution logistics.",
 "Ouvrez votre application bancaire": "Open your banking app",
 "Choisissez « Virement Interac »": "Choose \"Interac e-Transfer\"",
 "Collez l'adresse ci-dessous": "Paste the address below",
 "Copier": "Copy",
 "Copier l'adresse courriel de Phé-Nix": "Copy the Phé-Nix email address",
 "(Volet thérapie)": "(Treatment referrals)",
 "(Volet dépannage alimentaire)": "(Emergency food support)",
 "Chaque personne qui bénéficie du service prend connaissance du code d'éthique et des règlements généraux de Phé-Nix. Ce n'est pas une formalité : c'est ce qui permet à la distribution de se dérouler dans un cadre respectueux et sécuritaire, autant pour les personnes servies que pour les bénévoles.": "Everyone who uses the service reads Phé-Nix's code of ethics and general rules. This is not red tape: it is what allows a distribution to unfold in a respectful, safe setting, for the people served and the volunteers alike.",
 "Y a-t-il des règles à respecter pendant la distribution ?": "Are there rules to follow during a distribution?",
 "Oui. Chaque personne qui bénéficie du service prend connaissance du code d'éthique et des règlements généraux de Phé-Nix. Ils encadrent le déroulement de la distribution pour que tout se passe dans le respect de chacun, personnes servies comme bénévoles. Demandez-les à un bénévole sur place, ou": "Yes. Everyone who uses the service reads Phé-Nix's code of ethics and general rules. They set the framework for a distribution so that everyone is treated with respect, the people served and the volunteers alike. Ask a volunteer on site, or",
 "pour les recevoir.": "to receive a copy.",
 "Table de distribution installée sur un trottoir de Montréal": "Distribution table set up on a Montreal sidewalk",
 "Un bénévole de Phé-Nix prépare les caisses de fruits avant la distribution": "A Phé-Nix volunteer preparing crates of fruit before a distribution",
 "Collecte de pain invendu chez un commerçant partenaire": "Picking up unsold bread from a partner business",
 "Un panier d'épicerie contenant les effets personnels d'une personne sans domicile": "A shopping cart holding the belongings of someone without a home",
 "Le pick-up de Phé-Nix chargé, prêt pour la tournée": "The Phé-Nix pickup loaded and ready to roll",
 "Caisse de légumes récupérée chez un producteur maraîcher": "A crate of vegetables collected from a market grower",
 "Un bénévole en chandail Phé-Nix tient une toile offerte à l'organisme": "A volunteer in a Phé-Nix shirt holding a painting donated to the organisation",
 "La brigade de cuisine partenaire devant la bannière de Phé-Nix": "The partner kitchen brigade in front of the Phé-Nix banner",
 "Remise de denrées par un commanditaire à deux bénévoles de Phé-Nix": "A sponsor handing food over to two Phé-Nix volunteers",
 "Des pompiers partenaires devant la bannière de Phé-Nix": "Partner firefighters in front of the Phé-Nix banner",
 "Michel Couture avec un partenaire, au local de préparation": "Michel Couture with a partner at the preparation space",
 "Kiosque de Phé-Nix lors d'un événement communautaire": "The Phé-Nix booth at a community event",
 "Chaque transport est encadré par": "Every ride is handled by",
 "deux bénévoles, jamais un seul": "two volunteers, never just one",
 ". C'est une règle à laquelle nous ne dérogeons pas : elle protège la personne accompagnée autant que les bénévoles qui conduisent.": ". This is a rule we do not bend: it protects the person we are helping as much as the volunteers doing the driving.",
 "Pourquoi deux bénévoles pour un seul transport ?": "Why two volunteers for a single ride?",
 "Parce que personne ne devrait se retrouver seul en voiture avec quelqu'un qu'il connaît peu, ni d'un côté ni de l'autre. La présence de deux bénévoles protège la personne accompagnée comme celle qui conduit, et permet de réagir si le trajet ne se déroule pas comme prévu. C'est une condition, pas une préférence : sans deux bénévoles disponibles, le transport est reporté.": "Because nobody should end up alone in a car with someone they barely know, on either side. Having two volunteers protects the person being helped as much as the one driving, and means someone can react if the trip does not go as planned. It is a condition, not a preference: without two volunteers available, the ride is postponed.",
 "C'est": "It is",
 "Guy": "Guy",
 "qui s'occupe des dépannages alimentaires. Vous pouvez l'appeler directement au": "who handles emergency food support. You can call him directly at",
 ", pour vous-même ou pour quelqu'un d'autre qui a besoin d'aide.": ", for yourself or for someone else who needs help.",
 "Chaque demande est traitée selon les besoins de la personne et selon ce qui est disponible au moment de l'appel. Le service s'adresse à toute personne en situation de précarité alimentaire : il ne se limite pas aux personnes en situation d'itinérance. Une famille, un ménage, une personne seule qui n'arrive plus à remplir son frigo, tous peuvent faire une demande.": "Every request is handled according to the person's needs and to what is available at the time of the call. The service is open to anyone facing food insecurity: it is not limited to people experiencing homelessness. A family, a household, a person living alone who can no longer fill their fridge, all of them can make a request.",
 "Puis-je appeler pour quelqu'un d'autre ?": "Can I call on behalf of someone else?",
 "Oui. Beaucoup de gens n'appellent pas pour eux-mêmes. Si vous connaissez une personne ou une famille qui manque de nourriture, appelez Guy au": "Yes. Many people do not call for themselves. If you know a person or a family who is short of food, call Guy at",
 "et expliquez-lui la situation.": "and explain the situation.",
 "Uniquement par téléphone, en appelant Guy au": "By phone only, by calling Guy at",
 ". Le courriel et Facebook ne servent pas pour les demandes de dépannage : elles n'y sont pas traitées. Chaque demande est ensuite évaluée selon vos besoins et selon les denrées disponibles.": ". Email and Facebook are not used for emergency food requests: they are not processed there. Each request is then assessed according to your needs and to what food is available.",
 "Guy — dépannage alimentaire": "Guy — emergency food support",
 "Un seul numéro.": "One number, that's it.",
 "Le dépannage alimentaire se demande": "Emergency food support is requested",
 "uniquement par téléphone": "by phone only",
 ". Les demandes envoyées par courriel ou par Facebook ne sont pas traitées.": ". Requests sent by email or through Facebook are not processed.",
 "Appelez pour vous-même ou pour quelqu'un d'autre. Pour toute autre question sur Phé-Nix, écrivez-nous à": "Call for yourself or for someone else. For any other question about Phé-Nix, write to us at",
 "En plus ou moins 72 heures, on vous met en contact avec une ressource adaptée à votre réalité, pour vous ou pour un proche. On connaît le milieu, on oriente vers ce qui convient vraiment.": "In roughly 72 hours, we put you in touch with a resource suited to your reality, for you or for someone close to you. We know the field, we point people to what actually fits.",
 "Un exemple concret : une personne vit à Montréal et la ressource qui peut l'accueillir se trouve à trois heures de route. Sans voiture, ce trajet devient infranchissable. C'est précisément celui que nous prenons en charge.": "A concrete example: someone lives in Montreal and the resource that can take them is three hours away. With no car, that trip is a wall. It is exactly the one we take on.",
 "Ce n'est pas un service de navette et ce n'est pas pour des rendez-vous.": "This is not a shuttle service and it is not for appointments.",
 "C'est un déplacement ponctuel, sur une longue distance, pour rapprocher la personne de sa thérapie.": "It is a one-off, long-distance trip to bring the person closer to their treatment.",
 "Est-ce que vous m'amenez à mes rendez-vous ?": "Do you drive me to my appointments?",
 "Non. Le transport ne sert pas à se rendre à des rendez-vous, et ce n'est pas un service quotidien. Il sert à conduire une personne jusqu'à la région où se trouve sa thérapie quand celle-ci est éloignée : par exemple de Montréal vers une ressource située à trois heures de route. C'est ce long trajet-là, une fois, qui empêche souvent quelqu'un d'entrer en thérapie.": "No. The service is not for getting to appointments, and it is not a daily service. It is for driving someone to the area where their treatment is when it is far away: for instance from Montreal to a resource three hours down the road. That single long trip is often what stops someone from entering treatment at all.",
 "La demande peut être faite par la personne elle-même ou par un tiers : un proche, un ami, un intervenant.": "The request can be made by the person themselves or by a third party: a relative, a friend, a caseworker.",
 "Prestataire d'une aide sociale": "Social assistance recipient",
 "C'est ce qui permet de financer la thérapie vers laquelle nous orientons.": "That is what makes it possible to fund the treatment we point people to.",
 "Y a-t-il une condition pour être référé ?": "Is there a condition to be referred?",
 "Il faut être prestataire d'une aide sociale. C'est ce qui permet de financer la thérapie vers laquelle nous vous orientons. Si ce n'est pas votre cas, présentez-nous tout de même votre situation : nous verrons ce qui est possible.": "You need to be a social assistance recipient. That is what makes it possible to fund the treatment we point you to. If that is not your case, tell us about your situation anyway: we will look at what is possible.",
 "Distributions<br>par année": "Distributions<br>per year",
 "En plus ou moins 72 heures, nous vous mettons en contact avec une ressource adaptée à votre réalité, pour vous ou pour un proche. Nous connaissons le milieu et nous orientons vers la ressource appropriée.": "In roughly 72 hours, we put you in touch with a resource suited to your reality, for you or for someone close to you. We know the field and we point people to the right resource.",
 "Les personnes que nous accompagnons vers une thérapie. La demande peut être faite par la personne elle-même ou par un tiers : un proche, un ami, un intervenant. Le transport vient en complément de notre service de": "The people we support toward treatment. The request can be made by the person themselves or by a third party: a relative, a friend, a caseworker. The ride comes alongside our",
 "Articles de survie": "Survival gear",
 "Tentes, réchauds, sacs de couchage et tout matériel qui aide à passer la nuit dehors.": "Tents, camp stoves, sleeping bags and any gear that helps someone get through a night outdoors.",
 "0,60 $ du kilomètre": "$0.60 per kilometre",
 "Le coût moyen d'un transport, qui couvre l'essence et l'usage du véhicule.": "The average cost of a ride, covering fuel and vehicle wear.",
 "Combien coûte un transport ?": "How much does a ride cost?",
 "En moyenne 0,60 $ du kilomètre. Ce montant couvre l'essence et l'usage du véhicule, rien d'autre : aucun bénévole n'est payé. Parlez-nous de votre situation, nous évaluerons ensemble ce qui est possible.": "On average $0.60 per kilometre. That amount covers fuel and vehicle wear, nothing else: no volunteer is paid. Tell us about your situation and we will work out together what is possible.",
 "✓ Adresse copiée. Collez-la dans votre virement": "✓ Address copied, paste it into your transfer"
};

/* ===========================================================
   Bascule francais / anglais
   Le dictionnaire ci-dessus associe chaque texte francais du
   site a sa version anglaise. Le moteur parcourt la page,
   remplace les textes, et garde l'original en memoire pour
   pouvoir revenir au francais sans recharger.
   =========================================================== */
(function () {
  var CLE = 'phenix-langue';
  var ATTRS = ['alt', 'aria-label', 'title', 'placeholder', 'data-suffix'];
  var originaux = null;   // rempli au premier passage

  function norm(t) { return t.replace(/\s+/g, ' ').trim(); }

  /* Recense tous les endroits traduisibles, une seule fois. */
  function recenser() {
    if (originaux) return originaux;
    originaux = { textes: [], attributs: [], titre: document.title, meta: null };

    var promeneur = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
      acceptNode: function (n) {
        var p = n.parentNode;
        if (!p) return NodeFilter.FILTER_REJECT;
        var b = p.nodeName;
        if (b === 'SCRIPT' || b === 'STYLE' || b === 'NOSCRIPT') return NodeFilter.FILTER_REJECT;
        return norm(n.nodeValue) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    var n;
    while ((n = promeneur.nextNode())) {
      originaux.textes.push({ noeud: n, fr: n.nodeValue });
    }

    ATTRS.forEach(function (a) {
      var els = document.querySelectorAll('[' + a + ']');
      for (var i = 0; i < els.length; i++) {
        originaux.attributs.push({ el: els[i], attr: a, fr: els[i].getAttribute(a) });
      }
    });

    var m = document.querySelector('meta[name="description"]');
    if (m) originaux.meta = { el: m, fr: m.getAttribute('content') };

    return originaux;
  }

  /* Remplace en gardant les espaces d'origine autour du texte. */
  function traduire(brut) {
    var cle = norm(brut);
    var en = DICO[cle];
    if (!en) return null;
    var avant = brut.match(/^\s*/)[0];
    var apres = brut.match(/\s*$/)[0];
    return avant + en + apres;
  }

  function appliquer(langue) {
    var o = recenser();
    var versAnglais = (langue === 'en');

    o.textes.forEach(function (t) {
      if (versAnglais) {
        var en = traduire(t.fr);
        if (en !== null) t.noeud.nodeValue = en;
      } else {
        t.noeud.nodeValue = t.fr;
      }
    });

    o.attributs.forEach(function (a) {
      if (versAnglais) {
        var en = traduire(a.fr);
        if (en !== null) a.el.setAttribute(a.attr, en);
      } else {
        a.el.setAttribute(a.attr, a.fr);
      }
    });

    document.title = versAnglais ? (DICO[norm(o.titre)] || o.titre) : o.titre;
    if (o.meta) {
      o.meta.el.setAttribute('content',
        versAnglais ? (DICO[norm(o.meta.fr)] || o.meta.fr) : o.meta.fr);
    }

    document.documentElement.lang = versAnglais ? 'en' : 'fr';
    document.querySelectorAll('.lang-btn').forEach(function (b) {
      b.classList.toggle('actif', b.dataset.langue === langue);
    });
    try { localStorage.setItem(CLE, langue); } catch (e) {}
  }

  window.choisirLangue = appliquer;

  function demarrer() {
    var choisie = 'fr';
    try { choisie = localStorage.getItem(CLE) || 'fr'; } catch (e) {}
    if (choisie === 'en') appliquer('en');
    else document.querySelectorAll('.lang-btn').forEach(function (b) {
      b.classList.toggle('actif', b.dataset.langue === 'fr');
    });

    document.querySelectorAll('.lang-btn').forEach(function (b) {
      b.addEventListener('click', function () { appliquer(b.dataset.langue); });
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', demarrer);
  } else {
    demarrer();
  }
})();
